### ISSUE TITLE
配置settings后出现KeyError: 'getOriginPic'

### ISSUE THREAD

**Issue by Jezzffihuter** [junhaideng/Google_Image_Searcher#4]
你好！
感谢你的项目，我正在尝试使用这个来系统性搜索并下载相关图片。
目前我配置的是google_image_searcher_v6，系统环境是Windows 10，使用的是Python 3.8。测试图片文件夹（upload）如下：
![image](https://user-images.githubusercontent.com/65488456/150291636-9164d7bf-0b2d-4f07-b7c9-94c43eef5c68.png)
我似乎能够成功跑通settings.py（仅将mirror变为False，因为在墙外）。
![image](https://user-images.githubusercontent.com/65488456/150291762-ab93358b-acee-4bc9-9b7a-0b6be72fcc97.png)

但是，我遇到了如下问题：
![image](https://user-images.githubusercontent.com/65488456/150291910-7bee7ba3-4153-4563-bca8-0e3b0e4830f3.png)
请问这里的settings是一个package还是指的是settings.py?
如果是前者，settings这边显示我无法安装。
![image](https://user-images.githubusercontent.com/65488456/150292132-9340e085-9152-45c6-ac83-603574876200.png)

请问问题出在哪里（文件夹配置和settings问题）呢？可能有什么解决方法呢？
感谢帮助！
顺祝新年快乐~

**Comment by junhaideng** [comment]
settings 是本地的 `settings.py` 文件，如果报错的话，可以在当前目录夹添加一个 `__init.py__` 空文件，json 文件中没有 `getOriginPic` 这个字段，添加到文件中

镜像有点问题，直接外网的话可以试试最新的提交。

如果不行的话，不要使用最新的提交，用 470e8b5279aef570085db0aeeb166fb699387b9f ，也就是去掉另外一个同学的提交内容的代码。
```bash
git reset --hard 470e8b5279aef570085db0aeeb166fb699387b9f
```
或者试试 [go-gis](https://github.com/junhaideng/go-gis/releases) 二进制可执行文件

**Comment by chuyao-wang** [comment]
感谢回复！我修改了以下两处：
1）在目录中添加了__init.py__.py
![image](https://user-images.githubusercontent.com/65488456/150300831-e8c52fde-39ca-4687-a2ad-e3e90cde2e0e.png)
2）在json文件中添加了"getOriginPic" = true
![image](https://user-images.githubusercontent.com/65488456/150301222-fcb41b24-b8c9-41c2-9443-03f8894d1ff3.png)
settings.py仍然可以正常运行。

不过，再次运行main.py后报错。
![image](https://user-images.githubusercontent.com/65488456/150301563-69baf369-504c-4063-bf10-b951eeb61442.png)

请问是我改错了吗？欢迎建议。
抱歉我没学过计算机相关专业，如果方便，请稍稍具体讲一下debug步骤，感谢~

**Comment by junhaideng** [comment]
用 git reset 一下吧，先别用最新的版本吧，我这边没有VPN不好测试，debug的话，多打断点就好😂

**Comment by chuyao-wang** [comment]
我搜了一下，git reset 命令是回退版本
请问你的意思是用这里的哪一个版本？
![image](https://user-images.githubusercontent.com/65488456/150303852-efd2b006-919d-4d4f-9768-445b1b03cb4c.png)
顺便确认下，以上两点我有没有改错呢

**Comment by junhaideng** [comment]
没改错，把项目用 git clone 下来，然后到项目中执行 `git reset --hard 470e8b5279aef570085db0aeeb166fb699387b9f`，不了解的话，可以百度一下 git ~

**Comment by chuyao-wang** [comment]
好的我去看看~

**Comment by chuyao-wang** [comment]
你好，我搜了一下git clone，我半蒙半猜地尝试了一下。
似乎克隆到了本地目录，但是进一步的操作遇到困难。
![image](https://user-images.githubusercontent.com/65488456/150337270-1931b247-b375-40b2-b961-173a499cc8d4.png)
这主要是因为我没有很好理解“到项目中执行 git reset --hard 470e8b5279aef570085db0aeeb166fb699387b9f”具体如何操作。

另外，我看到前4版是用selenium，而后面似乎没有用，请问第5或6版会比前4版快得多吗？如果我第6版设置有困难，有无比较方便设置的版本呢~

新年快乐~

**Comment by yangn0** [comment]
> 感谢回复！我修改了以下两处： 1）在目录中添加了__init.py__.py ![image](https://user-images.githubusercontent.com/65488456/150300831-e8c52fde-39ca-4687-a2ad-e3e90cde2e0e.png) 2）在json文件中添加了"getOriginPic" = true ![image](https://user-images.githubusercontent.com/65488456/150301222-fcb41b24-b8c9-41c2-9443-03f8894d1ff3.png) settings.py仍然可以正常运行。
> 
> 不过，再次运行main.py后报错。 ![image](https://user-images.githubusercontent.com/65488456/150301563-69baf369-504c-4063-bf10-b951eeb61442.png)
> 
> 请问是我改错了吗？欢迎建议。 抱歉我没学过计算机相关专业，如果方便，请稍稍具体讲一下debug步骤，感谢~

最新版 在你修改的基础上 删除216 217 218行。219行 退一格缩进。

**Comment by yangn0** [comment]
#5

**Comment by junhaideng** [comment]
使用最新提交的代码~
